import {StartSpot, FinishSpot, BatterySpot, RandomSpot, ReverseSpot, EmptySpot} from '@/services/model/Spot';

export const MAPPINGS = {
    empty: EmptySpot,
    in: StartSpot,
    out: FinishSpot,
    battery: BatterySpot,
    random: RandomSpot,
    reverse: ReverseSpot
}

export const SCHEME = [
    {effect: 'in'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'out'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'},
    {effect: 'empty'}
];